#!/bin/sh
# This script is useful for when your Pictures directory is so huge and you want feh to pick a random file.
OUTPUT="$(ls $HOME/Pictures/wallpapers |shuf -n 1)"
feh --bg-scale $HOME/Pictures/wallapers/$OUTPUT
