#!/bin/bash

UPDATE="apt-get update"
UPGRADE="apt-get upgrade"
CHOICE="$1"

echo "Do you want to update your package repositories? (Case sensitive) [Y/n]: "
read $CHOICE

if [ "$CHOICE" = "Y" ]; then
	sudo $UPDATE
fi


echo "Do you want to upgradee your system? (Case sensitive) [Y/n]: "
read $CHOICE

if [ "$CHOICE" = "Y" ]; then
	sudo $UPGRADE
fi
